'use client'

import { useState } from 'react'
import { ArrowLeft, Bell, Check, ChevronDown, ChevronRight, Grid2X2, Home, MoreVertical, QrCode, ScanLine, Settings, UserRound } from 'lucide-react'

type Screen = 'welcome' | 'connect' | 'home' | 'accounts' | 'transactions' | 'profile' | 'transfer' | 'transfer-review' | 'transfer-success' | 'pay' | 'pay-confirm' | 'pay-success'
const money = (value: string) => `₱${Number(value || 0).toLocaleString('en-PH', { minimumFractionDigits: 2 })}`
const accounts = [{ name: 'GCash', type: 'E-Wallet', balance: '₱12,450', connected: true }, { name: 'Maya', type: 'E-Wallet', balance: '₱8,230', connected: true }, { name: 'MariBank', type: 'Savings Account', balance: '₱25,000', connected: true }, { name: 'BPI', type: 'Bank', balance: '—', connected: false }, { name: 'BDO', type: 'Bank', balance: '—', connected: false }]
const transactions = [['Grab', 'GCash • Food & Dining', '-₱250.00'], ['Coffee Bean', 'Maya • Food & Dining', '-₱180.00'], ['Salary', 'MariBank • Income', '+₱30,000.00'], ['Supermarket', 'GCash • Groceries', '-₱1,250.00'], ['PLDT Bill', 'BPI • Bills', '-₱1,899.00']]

export default function Page() {
  const [screen, setScreen] = useState<Screen>('welcome'); const [tab, setTab] = useState('home'); const [provider, setProvider] = useState(''); const [connectedNames, setConnectedNames] = useState(accounts.filter((account) => account.connected).map((account) => account.name)); const [verificationProvider, setVerificationProvider] = useState(''); const [verificationCode, setVerificationCode] = useState(''); const [amount, setAmount] = useState('2000'); const [source, setSource] = useState('GCash'); const [destination, setDestination] = useState('Maya'); const [activity, setActivity] = useState(transactions)
  const connectedAccounts = accounts.filter((account) => connectedNames.includes(account.name));
  const home = () => { setScreen('home'); setTab('home') }; const go = (s: Screen) => setScreen(s)
  const openConnect = (name: string) => { setProvider(name); if (!connectedNames.includes(name)) { setVerificationProvider(name); setVerificationCode('') } }
  const verifyConnection = () => { if (verificationCode.trim().length !== 6) return; setConnectedNames((current) => current.includes(verificationProvider) ? current : [...current, verificationProvider]); setVerificationProvider(''); setProvider(verificationProvider) }
  const addActivity = (kind: 'transfer' | 'payment') => { const account = kind === 'payment' ? source : source; const label = kind === 'payment' ? 'Coffee Shop' : destination; setActivity((current) => [[label, `${account} • ${kind === 'payment' ? 'Payment' : 'Transfer'}`, kind === 'payment' ? '-₱500.00' : `-₱${Number(amount).toLocaleString()}`], ...current]); home() }
  const verificationModal = verificationProvider ? <div className="modal-backdrop" role="presentation"><div className="verification-modal" role="dialog" aria-modal="true" aria-labelledby="verification-title"><button className="modal-close" onClick={() => setVerificationProvider('')} aria-label="Close verification">×</button><span className="modal-icon">▣</span><p className="eyebrow">SECURE CONNECTION</p><h2 id="verification-title">Verify {verificationProvider}</h2><p className="muted">We sent a mock verification code to your registered mobile number.</p><label>Verification code<input inputMode="numeric" maxLength={6} value={verificationCode} onChange={(e) => setVerificationCode(e.target.value.replace(/\\D/g, ''))} placeholder="Enter 6-digit code" autoFocus /></label><button className="black-button" onClick={verifyConnection} disabled={verificationCode.length < 4}>Verify and connect</button><button className="text-button" onClick={() => setVerificationProvider('')}>Cancel</button></div></div> : null
  if (screen === 'welcome') return <><main className="phone centered"><div className="wallet-logo">▣</div><h1>PeraFolio</h1><h2>All your money.<br />One place.</h2><p className="muted">Connect your banks and e-wallets to see your complete financial picture in one application.</p><button className="black-button" onClick={() => go('connect')}>Get Started</button><button className="outline-button" onClick={home}>Log In</button><p className="security">◉ Your financial data is protected and securely managed.</p></main>{verificationModal}</>
  if (screen === 'connect') return <><main className="phone"><Top title="Connect Your Accounts" back={() => go('welcome')} /><p className="subtitle">Bring your finances together in one place.</p><section className="connect-list">{accounts.map((a) => { const isConnected = connectedNames.includes(a.name); return <button className="connect-row" key={a.name} onClick={() => openConnect(a.name)}><span className="account-icon">▣</span><span className="row-copy"><b>{a.name}</b><small>{a.type}</small></span>{isConnected ? <small className="green status-label">Connected</small> : <span className="mini-black">Connect</span>}</button>})}</section><button className="black-button" onClick={home}>Continue</button><button className="text-button" onClick={home}>Connect Later</button></main>{verificationModal}</>
  if (screen === 'transfer') return <Transfer amount={amount} setAmount={setAmount} source={source} destination={destination} connectedAccounts={connectedAccounts} setSource={setSource} setDestination={setDestination} onBack={home} onReview={() => go('transfer-review')} />
  if (screen === 'transfer-review') return <Review kind="transfer" amount={amount} source={source} destination={destination} onBack={() => go('transfer')} onConfirm={() => { addActivity('transfer'); go('transfer-success') }} />
  if (screen === 'transfer-success') return <Success kind="transfer" title="Transfer Successful" amount={money(amount)} source={source} destination={destination} onDone={home} />
  if (screen === 'pay') return <Pay source={source} setSource={setSource} connectedAccounts={connectedAccounts} onBack={home} onReview={() => go('pay-confirm')} />
  if (screen === 'pay-confirm') return <Review kind="pay" amount="500" source={source} destination="Coffee Shop" onBack={() => go('pay')} onConfirm={() => { addActivity('payment'); go('pay-success') }} />
  if (screen === 'pay-success') return <Success kind="payment" title="Payment Successful" amount="₱500.00" source={source} destination="Coffee Shop" onDone={home} />
  return <main className="phone app"><header className="dashboard-header"><div><small>Good evening,</small><h2>Alessandra</h2></div><div className="header-actions"><Bell /><button className="icon-button" onClick={() => setTab('profile')} aria-label="Open profile and settings"><UserRound /></button></div></header>{tab === 'home' && <Dashboard activity={activity} onTransfer={() => go('transfer')} onPay={() => go('pay')} />}{tab === 'accounts' && <Accounts connectedNames={connectedNames} />}{tab === 'transactions' && <Transactions activity={activity} />}{tab === 'profile' && <Profile onBack={home} />}{tab !== 'profile' && <Bottom setTab={setTab} active={tab} onPay={() => go('pay')} />}</main>
}
function Top({ title, back }: { title: string; back: () => void }) { return <header className="top"><button onClick={back} aria-label="Back"><ArrowLeft /></button><div><h2>{title}</h2></div><span /></header> }
function Dashboard({ activity, onTransfer, onPay }: { activity: string[][]; onTransfer: () => void; onPay: () => void }) { const [period, setPeriod] = useState('This Month'); const [category, setCategory] = useState('All'); const chartHeights = period === 'Last Month' ? [42, 64, 50, 78, 60, 72, 48] : period === 'This Year' ? [76, 52, 84, 58, 90, 68, 82] : [28, 48, 36, 72, 54, 66, 44]; const visibleTransactions = category === 'All' ? activity.slice(0, 3) : activity.filter((transaction) => transaction[1].toLowerCase().includes(category.toLowerCase())).slice(0, 3); return <section className="content"><small>Total Balance</small><h1 className="total">₱45,680.00</h1><small>Across 3 connected accounts</small><div className="stats"><b>INCOME<strong>₱30,000</strong></b><b>SPENDING<strong>₱14,320</strong></b><b>SAVINGS<strong>₱15,680</strong></b></div><div className="section-title"><b>Spending Overview</b><label className="select-wrap"><select value={period} onChange={(e) => setPeriod(e.target.value)} aria-label="Spending period"><option>This Month</option><option>Last Month</option><option>This Year</option></select><ChevronDown size={14} /></label></div><div className="chart" aria-label={`${period} spending chart`}>{chartHeights.map((height, index) => <i key={`${period}-${index}`} style={{ height: `${height}%` }} />)}</div><div className="chips" role="group" aria-label="Transaction category filters">{['All', 'Food & Dining', 'Transportation', 'Shopping', 'Bills'].map((item) => <button className={category === item ? 'selected' : ''} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="section-title"><b>Recent Transactions</b><button>View All</button></div>{visibleTransactions.length ? visibleTransactions.map((t) => <Transaction t={t} key={t[0]} />) : <p className="empty-state">No {category.toLowerCase()} transactions this period.</p>}<div className="quick-bottom"><button onClick={onTransfer}>Transfer</button><button onClick={onPay}>Pay</button></div></section> }
function Accounts({ connectedNames }: { connectedNames: string[] }) { return <section className="content"><div className="section-title"><b>Your Accounts</b><button>＋</button></div><div className="account-total"><small>Total Balance</small><strong>₱45,680.00</strong><small>Across 3 connected accounts</small></div>{accounts.filter((a) => connectedNames.includes(a.name)).map((a) => <article className="account-item" key={a.name}><span className="account-icon">{a.name[0]}</span><div><b>{a.name}</b><small>{a.type}</small><strong>{a.balance}</strong></div><MoreVertical /></article>)}</section>}
function Transactions({ activity }: { activity: string[][] }) { const [accountFilter, setAccountFilter] = useState('All Accounts'); const [categoryFilter, setCategoryFilter] = useState('All Categories'); const [monthFilter, setMonthFilter] = useState('This Month'); return <section className="content"><div className="section-title"><b>Transactions</b><Settings size={17} /></div><div className="filters"><label className="filter-select"><select value={accountFilter} onChange={(e) => setAccountFilter(e.target.value)} aria-label="Account filter"><option>All Accounts</option><option>GCash</option><option>Maya</option><option>MariBank</option></select><ChevronDown size={12} /></label><label className="filter-select"><select value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)} aria-label="Category filter"><option>All Categories</option><option>Food & Dining</option><option>Income</option><option>Bills</option></select><ChevronDown size={12} /></label><label className="filter-select"><select value={monthFilter} onChange={(e) => setMonthFilter(e.target.value)} aria-label="Month filter"><option>This Month</option><option>Last Month</option><option>All Time</option></select><ChevronDown size={12} /></label></div>{activity.map((t, i) => <div className="dated" key={t[0]}>{i === 0 && <small>TODAY</small>}{i === 2 && <small>YESTERDAY</small>}{i === 4 && <small>18 OCT 2026</small>}<Transaction t={t} /></div>)}</section>}
function Transaction({ t }: { t: string[] }) { return <div className="transaction"><span className="account-icon">{t[0][0]}</span><div><b>{t[0]}</b><small>{t[1]}</small></div><strong className={t[2][0] === '+' ? 'green' : ''}>{t[2]}</strong></div> }
function Transfer({ amount, setAmount, source, destination, connectedAccounts, setSource, setDestination, onBack, onReview }: { amount: string; setAmount: (v: string) => void; source: string; destination: string; connectedAccounts: typeof accounts; setSource: (v: string) => void; setDestination: (v: string) => void; onBack: () => void; onReview: () => void }) { const destinations = connectedAccounts.filter((account) => account.name !== source); return <main className="phone"><Top title="Transfer Money" back={onBack} /><section className="form-content"><AccountSelect label="FROM" name={source} balance={connectedAccounts.find((account) => account.name === source)?.balance ?? '—'} options={connectedAccounts} onChange={setSource} /><AccountSelect label="TO" name={destination} balance={connectedAccounts.find((account) => account.name === destination)?.balance ?? '—'} options={destinations} onChange={setDestination} /><label className="amount-label"><span>Enter Amount</span><input aria-label="Transfer amount" inputMode="decimal" type="text" value={`₱ ${Number(amount || 0).toLocaleString()}`} onChange={(e) => setAmount(e.target.value.replace(/[^0-9]/g, ''))} /></label><input className="note" aria-label="Transfer note" type="text" placeholder="Add a note (optional)" /><Summary amount={amount} /><button className="black-button" onClick={onReview} disabled={!Number(amount)}>Review Transfer</button></section></main> }
function AccountSelect({ label, name, balance, options, onChange }: { label: string; name: string; balance: string; options: typeof accounts; onChange: (value: string) => void }) { return <label className="account-select"><small>{label}</small><span className="account-icon">{name[0]}</span><b>{name}<small>Balance: {balance}</small></b><select value={name} onChange={(event) => onChange(event.target.value)} aria-label={`${label} account`}>{options.map((account) => <option key={account.name} value={account.name}>{account.name}</option>)}</select><ChevronDown /></label> }
function Summary({ amount }: { amount: string }) { return <div className="summary"><span>Transfer amount <b>{money(amount)}</b></span><span>Transfer fee <b>₱15.00</b></span><hr /><strong>Total <b>{money(String(Number(amount || 0) + 15))}</b></strong></div> }
function Review({ kind, amount, source, destination, onBack, onConfirm }: { kind: string; amount: string; source: string; destination: string; onBack: () => void; onConfirm: () => void }) { const isPayment = kind === 'pay'; return <main className="phone review-screen"><Top title={isPayment ? 'Review Payment' : 'Review Transfer'} back={onBack} /><section className="review-content"><div className="merchant-summary"><div className="merchant-icon">{isPayment ? '☕' : destination[0]}</div><h2>{destination}</h2>{isPayment && <small>Merchant ID: CS-98213</small>}<strong>{money(amount)}</strong></div><p className="form-eyebrow">{isPayment ? 'PAY WITH' : 'TRANSFER FROM'}</p>{isPayment ? <div className="payment-source-list">{['GCash', 'Maya'].filter((name) => name === source || name !== source).map((name) => <button className={`source-card ${source === name ? 'selected' : ''}`} key={name} onClick={() => {}}><span className="account-icon">{name[0]}</span><b>{name}<small>Balance: {name === 'GCash' ? '₱12,450' : '₱8,230'}</small></b><span>{source === name ? '●' : '○'}</span></button>)}</div> : <div className="review-transfer-card"><span>From account <b>{source}</b></span><span>To account <b>{destination}</b></span></div>}<div className="charge-card"><span>Amount <b>{money(amount)}</b></span><span>Fee <b>{isPayment ? '₱0.00' : '₱15.00'}</b></span><hr /><strong>Total charged <b>{isPayment ? money(amount) : money(String(Number(amount) + 15))}</b></strong></div><button className="black-button" onClick={onConfirm}>{isPayment ? 'Confirm Payment' : 'Confirm Transfer'}</button><button className="text-button" onClick={onBack}>Cancel</button></section></main> }
function Pay({ source, setSource, connectedAccounts, onBack, onReview }: { source: string; setSource: (v: string) => void; connectedAccounts: typeof accounts; onBack: () => void; onReview: () => void }) { return <main className="phone"><Top title="Pay" back={onBack} /><section className="form-content pay-screen"><div className="pay-tabs"><b>Scan QR</b><span>Enter Details</span></div><div className="qr-frame"><ScanLine /><small>Align the QR code within the<br />frame to pay</small></div><b>Payment Source</b>{connectedAccounts.map((a) => <button className={`source-card ${source === a.name ? 'selected' : ''}`} key={a.name} onClick={() => setSource(a.name)}><span className="account-icon">{a.name[0]}</span><b>{a.name}<small>Balance: {a.balance}</small></b><span>●</span></button>)}<button className="black-button" onClick={onReview}>Scan to Pay</button></section></main> }
function Success({ kind, title, amount, source, destination, onDone }: { kind: 'payment' | 'transfer'; title: string; amount: string; source: string; destination: string; onDone: () => void }) { const isPayment = kind === 'payment'; return <main className="phone success"><div className="success-icon"><Check /></div><h2>{title}</h2><h1>{amount}</h1><div className="success-card"><span>{isPayment ? 'PAID TO' : 'TRANSFERRED TO'} <b>{destination}</b></span><span>{isPayment ? 'PAID FROM' : 'TRANSFERRED FROM'} <b>{source}</b></span><span>DATE & TIME <b>20 Oct 2026, 14:30</b></span><span>REFERENCE <b>TXN-00012345</b></span></div><div className="success-balance"><span className="account-icon">{source[0]}</span><b>{source} Balance</b><strong>{isPayment ? '₱11,950' : '₱10,435'}</strong></div><button className="black-button" onClick={onDone}>Done</button></main> }
function Profile({ onBack }: { onBack: () => void }) { return <section className="content profile"><div className="section-title"><b>Profile & Settings</b><button onClick={onBack}>Done</button></div><div className="profile-card"><span className="profile-avatar">A</span><div><b>Alessandra</b><small>alessandra@perafolio.app</small></div></div>{['Personal details', 'Notifications', 'Security', 'Help & support'].map((item) => <button className="settings-row" key={item}>{item}<ChevronRight size={16} /></button>)}</section> }
function Bottom({ setTab, active, onPay }: { setTab: (v: string) => void; active: string; onPay: () => void }) { return <nav className="bottom"><button className={active === 'home' ? 'active' : ''} onClick={() => setTab('home')}><Home />Home</button><button className={active === 'transactions' ? 'active' : ''} onClick={() => setTab('transactions')}><ChevronRight />Activity</button><button onClick={onPay}><QrCode />Pay</button><button className={active === 'accounts' ? 'active' : ''} onClick={() => setTab('accounts')}><Grid2X2 />Accounts</button></nav> }
